name: Build and test
'on':
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install tox
      - run: tox --skip-missing-interpreters
